name: full_game_ui
description: Full Game UI Base
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.17.0
  audioplayers: ^5.2.1
  model_viewer_plus: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # 📦 তোমার সব থ্রিডি মডেলগুলো এখানে রেজিস্টার করা হলো
  assets:
    - assets/models/player.glb
    - assets/models/map.glb
    - assets/models/char1.glb
    - assets/models/char2.glb
    - assets/models/char3.glb
    - assets/models/sword.glb
    - assets/models/phoenix_bird.glb  # 👈 ফাইলের সঠিক নাম দেওয়া হয়েছে
    
